W2D1 curriculum specialist & day lead updates
neuromatch/climate-course-content pull request #31
Opened 2024-04-05 03:41 UTC by BrodiePearson

This PR replaces last year's W2D1 tutorials with this years updated set of 4 tutorials.

Checked with Python 3.9 locally

2024-04-11 13:47 UTC, iamzoltan requested changes
Nice Updates! There are somethings wrong your with PR. We need to address them before we can merge.

Todo:

- [ ]  Before saving, clear all outputs and restart your kernel.
- [ ]  Make sure to use a python environment with py3.9
- [ ]  Naming consistency. Your kaggle/colab links should point to the tutorials they are embedded in
- [ ]  Your tutorials days must also be consistent, increasing starting from 1. 
- [ ]  You should change your materials file to reflect the changes in the number of tutorials for that day

Please add those changes to your PR.

Additionally, please add me as production editor to the tutorials.

Let me know if you have any questions.

2024-04-11 13:47 UTC, iamzoltan commented on tutorials/W2D1_FutureClimate-IPCCIPhysicalBasis/W2D1_Tutorial1.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAA20AAAI/CAYAAADkwzGCAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjguMCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy81sbWrAAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOz
This image should not be here.

2024-04-11 13:47 UTC, iamzoltan commented on tutorials/W2D1_FutureClimate-IPCCIPhysicalBasis/W2D1_Tutorial1.ipynb
>   "nbformat": 4,
looks like you have the wrong python version.

2024-04-11 13:47 UTC, iamzoltan commented on tutorials/W2D1_FutureClimate-IPCCIPhysicalBasis/W2D1_Tutorial2.ipynb
> +    "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/neuromatch/climate-course-content/blob/main/tutorials/W2D1_FutureClimate-IPC
again, these tutorial links should reflect the names of the files themselves

2024-04-12 05:29 UTC, BrodiePearson commented
@iamzoltan I have updated the PR to fix all the issues you mentioned. I won't be able to address any other significant changes until next week.

2024-04-12 19:51 UTC, closed without merging