W2 D3 curriculum specialist & day lead updates
neuromatch/climate-course-content pull request #32
Opened 2024-04-05 15:00 UTC by nsea-log

New T1 to T4 and T6, T5 included but needs tbd.

2024-04-11 14:00 UTC, iamzoltan requested changes
Great work @nsea-log !! Just a few minor tweaks.

- [ ]  Look into the odd metadata behaviour
- [ ]  Remove the left over merge conflict text
- [ ]  Fix kernel

Really good work! 

p.s do you want to leave in the todos for now?

2024-04-12 17:35 UTC, nsea-log commented on tutorials/W2D3_FutureClimate-IPCCII&IIISocio-EconomicBasis/W2D3_Tutorial4.ipynb
>    },
None.

2024-04-12 17:39 UTC, nsea-log commented on tutorials/W2D3_FutureClimate-IPCCII&IIISocio-EconomicBasis/W2D3_Tutorial4.ipynb
>    },
Changed it manually.

2024-04-12 18:44 UTC, iamzoltan approved these changes
looks great!

2024-04-12 18:44 UTC, merged